#!/bin/bash

# Investment Analyst AI Agent - Quick Reference
# Copy this file for easy access to common commands

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Investment Analyst AI Agent - Quick Commands"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 ACCESS POINTS"
echo "  Frontend:    http://localhost:8501"
echo "  Backend:     http://localhost:8000"
echo "  API Docs:    http://localhost:8000/api/docs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 START/STOP COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Start everything:"
echo "  ./scripts/start_all.sh"
echo ""
echo "Start backend only:"
echo "  ./scripts/start_backend.sh"
echo ""
echo "Start frontend only:"
echo "  ./scripts/start_frontend.sh"
echo ""
echo "Stop services:"
echo "  Press Ctrl+C"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔧 DEVELOPMENT COMMANDS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Setup project:"
echo "  make setup"
echo ""
echo "Run tests:"
echo "  make test"
echo ""
echo "Format code:"
echo "  make format"
echo ""
echo "Clean temp files:"
echo "  make clean"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 DEPENDENCIES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Install dependencies:"
echo "  pip install -r requirements.txt"
echo ""
echo "Activate virtual environment:"
echo "  source venv/bin/activate"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🧪 TESTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run all tests:"
echo "  pytest tests/ -v"
echo ""
echo "Health check:"
echo "  curl http://localhost:8000/api/health"
echo ""
echo "Test file upload:"
echo "  curl -X POST http://localhost:8000/api/v1/files/upload \\"
echo "    -F 'file=@yourfile.pdf' \\"
echo "    -F 'category=financial'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📚 DOCUMENTATION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  SUCCESS.md       - You are here! Current status"
echo "  GET_STARTED.md   - Quick start guide"
echo "  QUICKSTART.md    - Detailed setup"
echo "  README.md        - Project overview"
echo "  DEVELOPMENT.md   - Developer guide"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🐛 TROUBLESHOOTING"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Kill process on port 8000:"
echo "  lsof -ti:8000 | xargs kill -9"
echo ""
echo "Kill process on port 8501:"
echo "  lsof -ti:8501 | xargs kill -9"
echo ""
echo "View logs:"
echo "  tail -f logs/app.log"
echo ""
echo "Reinstall dependencies:"
echo "  pip install -r requirements.txt --force-reinstall"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ QUICK START"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Start app:      ./scripts/start_all.sh"
echo "2. Open browser:   http://localhost:8501"
echo "3. Upload files:   Click 'Upload Documents'"
echo "4. View library:   Click 'Document Library'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
